dist: xenial
language: python
cache: pip
python:
  - "3.7"
notifications:
  email: false
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - pip install --upgrade pip
  - pip install pep8
  - pip install autopep8
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install setuptools
  - conda install conda
  - conda update --force conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH
  - pip install -r requirements-dev.txt
  - conda install numpy
  - conda install numba
  - pip install quadpy
  
script:
 - pytest -s

after_success:
  # Combine coverage reports from Travis jobs
  - coverage combine --append
  - coveralls
  - codecov
notifications:
  webhooks:
    - https://coveralls.io/webhook