name: ssqueezepy
channels:
  - conda-forge
  - defaults
  - numba
dependencies:
  - conda-build
  - pytest
  - pytest-cov
  - pycodestyle
  - pip
  - python >=3.10
  - numpy
  - scipy 
  - matplotlib 
  - librosa 
  - pyfftw
  - numba